"""Optional FastAPI service for real-time fraud scoring.

Serves the same model bundle generated by training code, so API and batch
scoring remain consistent.

Run
---
    uv run uvicorn app:app --reload

Optional authentication
-----------------------
If ``FRAUD_API_KEY`` is set in the environment, include ``X-API-Key`` in
``/score`` and ``/admin/reload-model`` requests.

Optional rate limiting
----------------------
Set ``FRAUD_RATE_LIMIT_PER_MIN`` (default: 120) to bound score requests per
client key (IP or forwarded-for header).
"""

from __future__ import annotations

import logging
import os
import time
from collections import defaultdict, deque
from dataclasses import dataclass
from pathlib import Path
from typing import Annotated, Literal

import pandas as pd
from fastapi import Depends, FastAPI, Header, HTTPException, Request
from pydantic import BaseModel, ConfigDict, Field

from src.scoring import FraudScorer

LOGGER = logging.getLogger("payment_fraud_api")
APP_DIR = Path(__file__).resolve().parent
DEFAULT_MODEL_PATH = APP_DIR / "models" / "fraud_scorer.joblib"


@dataclass
class RateLimiter:
    """In-memory per-client fixed-window rate limiter."""

    limit_per_window: int
    window_seconds: int = 60

    def __post_init__(self) -> None:
        self.limit_per_window = max(self.limit_per_window, 0)
        self._hits: dict[str, deque[float]] = defaultdict(deque)

    def allow(self, key: str, now: float | None = None) -> bool:
        """Return True if request should pass, False when rate-limited."""
        if self.limit_per_window <= 0:
            return True

        ts = time.monotonic() if now is None else now
        cutoff = ts - self.window_seconds
        bucket = self._hits[key]
        while bucket and bucket[0] <= cutoff:
            bucket.popleft()

        if len(bucket) >= self.limit_per_window:
            return False

        bucket.append(ts)
        return True


def _bool_env(name: str, default: bool) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def _int_env(name: str, default: int) -> int:
    raw = os.getenv(name)
    if raw is None:
        return default
    try:
        return max(0, int(raw))
    except ValueError:
        LOGGER.warning("Invalid integer value for %s=%r. Using default=%d.", name, raw, default)
        return default


def _configured_model_path() -> Path:
    raw = os.getenv("FRAUD_MODEL_PATH")
    if not raw:
        return DEFAULT_MODEL_PATH
    candidate = Path(raw).expanduser()
    if not candidate.is_absolute():
        candidate = APP_DIR / candidate
    return candidate.resolve()


def _load_scorer(model_path: Path) -> FraudScorer | None:
    if not model_path.exists():
        LOGGER.warning(
            "Model bundle not found at %s. Run training and save artifact first.",
            model_path,
        )
        return None

    require_hash = _bool_env("FRAUD_REQUIRE_MODEL_HASH", default=True)
    try:
        return FraudScorer.load(model_path, verify_hash=True, require_hash=require_hash)
    except Exception:
        LOGGER.exception("Failed to load fraud scorer artifact from %s.", model_path)
        return None


def _expected_api_key() -> str | None:
    value = os.getenv("FRAUD_API_KEY")
    return value.strip() if value else None


def _auth_guard(
    x_api_key: Annotated[str | None, Header(alias="X-API-Key")] = None,
) -> None:
    expected = _expected_api_key()
    if expected and x_api_key != expected:
        raise HTTPException(status_code=401, detail="Invalid API key.")


def _client_key(request: Request) -> str:
    forwarded_for = request.headers.get("x-forwarded-for")
    if forwarded_for:
        return forwarded_for.split(",")[0].strip()

    if request.client and request.client.host:
        return request.client.host

    return "unknown"


def _rate_limit_guard(request: Request) -> None:
    limiter: RateLimiter = request.app.state.rate_limiter
    key = _client_key(request)
    if not limiter.allow(key):
        raise HTTPException(status_code=429, detail="Rate limit exceeded. Try again later.")


app = FastAPI(
    title="Payment Fraud Risk Scoring",
    description="Scores a card transaction and returns its fraud risk.",
    version="0.3.0",
)

app.state.model_path = _configured_model_path()
app.state.scorer = _load_scorer(app.state.model_path)
app.state.rate_limiter = RateLimiter(limit_per_window=_int_env("FRAUD_RATE_LIMIT_PER_MIN", 120))


class Transaction(BaseModel):
    """One transaction with the exact feature schema used at training."""

    model_config = ConfigDict(extra="forbid")

    Time: float = Field(..., description="Seconds since the first transaction.")
    V1: float
    V2: float
    V3: float
    V4: float
    V5: float
    V6: float
    V7: float
    V8: float
    V9: float
    V10: float
    V11: float
    V12: float
    V13: float
    V14: float
    V15: float
    V16: float
    V17: float
    V18: float
    V19: float
    V20: float
    V21: float
    V22: float
    V23: float
    V24: float
    V25: float
    V26: float
    V27: float
    V28: float
    Amount: float = Field(..., ge=0, description="Transaction amount.")


class ScoreResponse(BaseModel):
    fraud_probability: float
    risk_score: int
    risk_band: str
    is_flagged: int
    threshold: float


class HealthResponse(BaseModel):
    status: Literal["ok", "degraded"]
    model_loaded: bool
    model_path: str
    rate_limit_per_min: int


def _get_scorer(request: Request) -> FraudScorer:
    scorer = request.app.state.scorer
    if scorer is None:
        raise HTTPException(
            status_code=503,
            detail=(
                "Fraud scorer model is not loaded. "
                "Train and save models/fraud_scorer.joblib, then restart or reload."
            ),
        )
    return scorer


@app.get("/health", response_model=HealthResponse)
def health(request: Request) -> HealthResponse:
    """Liveness and model-readiness check."""
    loaded = request.app.state.scorer is not None
    return HealthResponse(
        status="ok" if loaded else "degraded",
        model_loaded=loaded,
        model_path=str(request.app.state.model_path),
        rate_limit_per_min=int(request.app.state.rate_limiter.limit_per_window),
    )


@app.post(
    "/admin/reload-model",
    response_model=HealthResponse,
    dependencies=[Depends(_auth_guard)],
)
def reload_model(request: Request) -> HealthResponse:
    """Reload scorer artifact from disk without restarting the process."""
    request.app.state.scorer = _load_scorer(request.app.state.model_path)
    return health(request)


@app.post(
    "/score",
    response_model=ScoreResponse,
    dependencies=[Depends(_auth_guard), Depends(_rate_limit_guard)],
)
def score(txn: Transaction, request: Request) -> ScoreResponse:
    """Score a single transaction."""
    scorer = _get_scorer(request)
    row = pd.DataFrame([txn.model_dump(mode="python")])

    try:
        scored = scorer.score_frame(row, copy_input=False).iloc[0]
    except ValueError as exc:
        raise HTTPException(status_code=422, detail=str(exc)) from exc
    except HTTPException:
        raise
    except Exception as exc:  # pragma: no cover - defensive wrapper
        LOGGER.exception("Unexpected scoring failure.")
        raise HTTPException(status_code=500, detail="Internal scoring error.") from exc

    return ScoreResponse(
        fraud_probability=float(scored["fraud_probability"]),
        risk_score=int(scored["risk_score"]),
        risk_band=str(scored["risk_band"]),
        is_flagged=int(scored["is_flagged"]),
        threshold=float(scorer.threshold),
    )
